"""add batch indexes

Revision ID: a324c82d5742
Revises: 608f62c5ca65
Create Date: 2026-03-13 14:21:00.973721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a324c82d5742'
down_revision: Union[str, Sequence[str], None] = '608f62c5ca65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_state'))
        batch_op.drop_index(batch_op.f('ix_batches_application_id'))

    # ### end Alembic commands ###
